### ISSUE TITLE
Error on send message

### ISSUE THREAD

**Issue by LucaTomei** [pepes97/pepes97.github.io#1]
Sveva I was browsing your site and wanted to send you a message but I realized the form is not working.

<img width="1440" alt="Schermata 2021-10-05 alle 15 39 40" src="https://user-images.githubusercontent.com/46397302/136034310-c27b3ea7-e2eb-4324-bac2-0edcfec6b20f.png">

Little tip: GitHub Pages doesn't support php files, if I was you I would give a look to this [beautiful and simple trick](https://www.youtube.com/watch?v=PMN-cl7EmIM).

**Comment by pepes97** [comment]
Thanks luca! I followed your advice and now it works! If you have any other advice for me, go ahead!
